spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hb_emmployee
    username: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: hb_emmployee
server:
  port: 8082
  


  